image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_FILES: noiseTool/*

cache:
  key:
    prefix: ${CI_JOB_NAME}
    files:
      - poetry.lock
      - .gitlab-ci.yml
  paths:
    - .venv
    - .cache/pip
    - venv/
  when: on_success

stages:
  - linter
  - test
  - deploy
  - evaluate

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

Linter:
  stage: linter
  script:
    - poetry run flake8 --version
    - echo $PYTHON_FILES
    - poetry run flake8 --ignore=E501 --format junit-xml $PYTHON_FILES > linter.xml
  artifacts:
    when: always
    reports:
      junit: linter.xml

Unit Tests:
  stage: test
  script:
    - poetry run coverage run -m pytest -v --junitxml=report.xml
    - poetry run coverage report -m
    - poetry run coverage xml -o coverage/cobertura-coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

Package Registry:
  stage: deploy
  needs: [Unit Tests]
  script:
    - poetry version patch
    - git config user.email "bodensee@mytum.de"
    - git config user.name "GitLab Pipeline"
    - git config remote.gitlab_origin.url >&- || git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.lrz.de/robust-devops/students/noise-project-bodensee.git
    - git remote set-url gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.lrz.de/robust-devops/students/noise-project-bodensee.git
    - git add .
    - git commit -m "AUTO version increase"
    - git push gitlab_origin HEAD:main -o ci.skip

    - poetry build
    - poetry config repositories.gitlab https://gitlab.lrz.de/api/v4/projects/$CI_PROJECT_ID/packages/pypi
    - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry publish --repository gitlab
  only:
    - main
  when: manual

pages:
  stage: deploy
  script:
    - poetry run pdoc --output-dir public ./noiseTool
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Base Image:
  image: docker:latest
  stage: evaluate
  services:
    - name: docker:dind # required for docker-in-docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
       tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
       tag=":$CI_COMMIT_REF_SLUG"
       echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
       echo "Pushing to $CI_REGISTRY_IMAGE/base_image${tag}"
      fi
    - docker build --pull --no-cache -t "$CI_REGISTRY_IMAGE/base_image${tag}" evaluation_data/base_image
    - docker push "$CI_REGISTRY_IMAGE/base_image${tag}"
    - echo "tag=$tag" > build.env
  artifacts:
    when: on_success
    expire_in: 1 day
    reports:
      dotenv: build.env

Shiki:
  image: docker:latest
  stage: evaluate
  needs: 
    - job: Base Image
      artifacts: true
  services:
    - name: docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull --no-cache -t "$CI_REGISTRY_IMAGE/shiki" evaluation_data/shiki --build-arg tag="$tag"

Github Docs:
  image: docker:latest
  stage: evaluate
  needs: 
    - job: Base Image
      artifacts: true
  services:
    - name: docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull --no-cache -t "$CI_REGISTRY_IMAGE/evaluate_docs" evaluation_data/docs --build-arg tag="$tag"
    - docker run --cap-add=NET_ADMIN "$CI_REGISTRY_IMAGE/evaluate_docs"