image: python:3.10

stages:
  - test
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install
  - poetry add coverage

Unit Tests:
  stage: test
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  script:
    - poetry run coverage run -m pytest  -v --junitxml=report.xml
    - poetry run coverage xml -o coverage/cobertura-coverage.xml
