image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: 
    prefix: ${CI_JOB_NAME}
    files:
      - poetry.lock
      - .gitlab-ci.yml
  paths: 
    - .venv
    - .cache/pip
    - venv/
  when: on_success

stages:
  - test
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

Unit Tests:
  stage: test
  artifacts:
    when: always
    reports:
      junit: report.xml
  script:
    - poetry run pytest -v --junitxml=report.xml
